# Generated by Django 3.2.9 on 2021-11-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='has_orientation',
        ),
        migrations.AddField(
            model_name='graphic',
            name='orientation',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=20),
        ),
        migrations.AddField(
            model_name='graphic',
            name='size',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('a5', 'A5'), ('a4', 'A4'), ('a3', 'A3'), ('a2', 'A2')], max_length=20),
        ),
    ]
