# Generated by Django 3.2.9 on 2021-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_auto_20211115_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='requirement',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='orientation',
            field=models.CharField(blank=True, choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], max_length=20),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='size',
            field=models.CharField(blank=True, choices=[('a5', 'A5'), ('a4', 'A4'), ('a3', 'A3'), ('a2', 'A2')], max_length=20),
        ),
    ]
