# Generated by Django 3.2.9 on 2021-11-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20211115_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='star_count',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.TextField(default='', max_length=10),
        ),
    ]
